#!/bin/sh
ssh ubuntu@13.125.98.1 <<EOF
  cd ~/Back-End
  sudo rm ~/Back-End/package-lock.json
  git pull origin master
  npm install
  npx tsc
  sudo pm2 kill
  sudo pm2 start ~/Back-End/dist/server1.js -i max
  exit
EOF