#!/bin/sh
ssh ubuntu@13.124.150.142 <<EOF
  echo "> PORT : $PORT"
  echo "> SECRET_KEY : $SECRET_KEY"
  echo "> SALT : $SALT"
  echo "> NODE_ENV : $NODE_ENV"
  echo "> DB_HOST : $DB_HOST"
  echo "> DB_USER : $DB_USER"
  echo "> DB_PW : $DB_PW"
  echo "> DB_NAME : $DB_NAME"
  echo "> REDIS_HOST : $REDIS_HOST"
  echo "> REDIS_PORT : $REDIS_PORT"
  sudo docker pull hch950627/chang:2.0
  sudo docker image prune -f
  sudo docker kill antsori
  sudo docker rm antsori
  source /etc/profile.d/env.sh
  sudo docker run --name antsori \
  --env PORT=$PORT -e SECRET_KEY=$SECRET_KEY \
  --env SALT=$SALT -e NODE_ENV=$NODE_ENV \
  --env DB_HOST=$DB_HOST \
  --env DB_PW=$DB_PW \
  --env DB_NAME=$DB_NAME \
  --env REDIS_HOST=$REDIS_HOST \
  --env REDIS_PORT=$REDIS_PORT \
  -p 3000:3000 \
  -it -d hch950627/chang:2.0
  exit 
EOF
