#!/bin/sh
ssh ubuntu@13.124.150.142 <<EOF
  sudo docker pull hch950627/chang:2.0

  source /etc/profile.d/env.sh

  echo "> PORT : $PORT"
  echo "> SECRET_KEY : $SECRET_KEY"
  echo "> SALT : $SALT"
  echo "> NODE_ENV : $NODE_ENV"
  echo "> DB_HOST : $DB_HOST"
  echo "> DB_USER : $DB_USER"
  echo "> DB_PW : $DB_PW"
  echo "> DB_NAME : $DB_NAME"
  echo "> REDIS_HOST : $REDIS_HOST"
  echo "> REDIS_PORT : $REDIS_PORT"

  sudo docker image prune -f
  sudo docker kill antsori
  sudo docker rm antsori

  sudo docker run -p 3000:3000 \
  --name antsori \
  -v /home/ubuntu/env/.env:/Back-End/.env \
  -it -d hch950627/chang:2.0

  exit 
EOF
